import os
import secrets
from dotenv import load_dotenv

load_dotenv()

### Web hosting (SFTP) configuration
AICALART_SFTP_SERVER = os.getenv("AICALART_SERVER")
AICALART_SFTP_USERNAME = os.getenv("AICALART_USERNAME")
AICALART_SFTP_PASSWORD = os.getenv("AICALART_PASSWORD")
AICALART_BASE_URL = os.getenv("AICALART_BASE_URL")
AICALART_IMAGES_PATH = os.getenv("AICALART_IMAGES_PATH")
AICALART_PROMPTS_PATH = os.getenv("AICALART_PROMPTS_PATH")

### Image settings
OPENROUTER_AICALART_API_KEY = os.getenv("OPENROUTER_AICALART_API_KEY")
OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"
GPT_MODEL = "google/gemini-2.5-flash"
IMAGE_MODEL = 'google/gemini-3-pro-image-preview'  # Nano Banana Pro
PORTRAIT_ASPECT_RATIO = '9:16'
LANDSCAPE_ASPECT_RATIO = '16:9'
IMAGE_SIZE = '2K'

### Google Calendar
GOOGLE_CALENDAR_ID = os.getenv("GOOGLE_CALENDAR_ID")
SCOPES = ["https://www.googleapis.com/auth/calendar.readonly"]

### Prompt styles
# You can change this to what you want in .env via `ALWAYS_INCLUDE_IN_PROMPT`
ALWAYS_INCLUDE_IN_PROMPT = os.getenv(
    "ALWAYS_INCLUDE_IN_PROMPT",
    "You always place your two beloved domestic shorthair cats in every piece you create: Morty the black and white tuxedo, and Maisie the Abyssian Tabby mix.",
)

STYLE_BASES = [
    "1910's black and white newspaper satirical comic drawings",
    "3D objects on flat surfaces",
    "3D scribbles",
    "Acid Western",
    "Alien Botanical Gardens",
    "American Western landscape",
    "Ancient Astronaut Ruins",
    "Antigravity Architecture",
    "Aqueous Abstractions",
    "Arabesque calligraphy",
    "Arachnid Artistry",
    "Arcadian Afterlife",
    "Arcane Alchemy",
    "Arctic Aurora",
    "Art Deco architecture",
    "Art Informel",
    "Art Nouveau poster",
    "Arte Povera",
    "Ashcan School",
    "Assemblage art",
    "Astral Automata",
    "Auroral Abstracts",
    "Baroquerior",
    "Basquiat",
    "Bioluminescent Underwater World",
    "Bionic Fauna",
    "Bosch",
    "Botticelli",
    "Bruegel",
    "Candy-Colored Nightmares",
    "Caravaggio",
    "Castle Rave",
    "Cezanne",
    "Chagall",
    "Chimeric Creatures",
    "Chronicle Carvings",
    "Chrono-Collages",
    "Color Field Painting",
    "Conceptual Art",
    "Constable",
    "Courbet",
    "Crystalline Constructs",
    "Cubist still life",
    "Cyber-Gothic Cathedral",
    "Cyber-Primitive Wilderness",
    "Cybernetic Calligraphy",
    "Cyberpunk alleyway",
    "Da Vinci",
    "Dadaism",
    "Dali",
    "De Stijl",
    "Degas",
    "Digital Nomad Diaries",
    "Digital painting",
    "Dimensional Doorways",
    "Dreamcatcher Webs",
    "Dystopian Megacity",
    "Earthworks",
    "Eco-Futurist Habitats",
    "El Greco",
    "Electromagnetic Elegance",
    "Elemental Elegance",
    "Environmental art",
    "Ephemeral Embroidery",
    "Ethereal Light Showers",
    "European abstract painting",
    "Expressionist urban scene",
    "Fauvism",
    "Fluxus movement",
    "Fossilized Futures",
    "Fractal Fantasy",
    "Frozen Fantasies",
    "Futurism dynamic movement",
    "Garden of eden",
    "Gauguin",
    "Geothermal Graffiti",
    "Ghostly Victorian Manor",
    "Goya",
    "Graffiti street art",
    "Gravitational Graffiti",
    "Greco-Roman inspiration",
    "Happenings",
    "Hard-Edge Painting",
    "Haring",
    "Harlem Renaissance vibrancy",
    "High Renaissance",
    "Hokusai",
    "Holographic Histories",
    "Hopper",
    "Hyperbolic Horizons",
    "Hyperrealistic",
    "Ice Age Revival",
    "Impressionist landscape",
    "Invisible Cities",
    "Iridescent Illusions",
    "Japanese ukiyo-e woodblock prints",
    "Kahlo",
    "Kandinsky",
    "Klee",
    "Klimt",
    "Kubrick",
    "LSD-inspired",
    "Liquid Light Art",
    "Lowbrow",
    "Luminous Labyrinths",
    "Lunar Land Art",
    "Lunar Landscapes",
    "Lunar Linocuts",
    "Lunar Lithographs",
    "Lunar Lithography",
    "Lunar Monuments",
    "Lyrical Abstraction",
    "Magic Realism",
    "Magnetic Murals",
    "Magritte",
    "Manet",
    "Matisse",
    "Mechanical Renaissance",
    "Medieval illuminated manuscript",
    "Metal lithograph",
    "Michelangelo",
    "Minimalist abstract art",
    "Modigliani",
    "Monet",
    "Morisot",
    "Mr. Rogers Neighborhood",
    "Munch",
    "Mutant Metropolis",
    "Mystic Mandalas",
    "Mystical Library",
    "Mythical Mosaics",
    "Nano-Art",
    "Nanotech Nostalgia",
    "Nautical Nouveau",
    "Nebular Needlework",
    "Neo-Baroque",
    "Neo-Dada",
    "Neo-Expressionism",
    "Neo-Geo",
    "Neo-plasticism",
    "Neoclassicism",
    "Neon Jungle",
    "Nouveau Réalisme",
    "O'Keeffe",
    "Oceanic Opulence",
    "Oceanic Oracles",
    "Op Art",
    "Orbital Ornaments",
    "Outsider Art",
    "Phantasmagoric Portals",
    "Phantom Orchestra",
    "Photonic Paintings",
    "Photorealism",
    "Picasso",
    "Pictorial Puzzles",
    "Pissarro",
    "Plasma Portraits",
    "Polarized Panoramas",
    "Pollock",
    "Polydimensional Paintings",
    "Pop Art collage",
    "Post-Apocalyptic Nomad Tribes",
    "Post-Impressionism",
    "Post-Modernism",
    "Postminimalism",
    "Psychedelic art",
    "Quantum Jungle",
    "Quantum Quilts",
    "Raphael",
    "Rayonism",
    "Rembrandt",
    "Renaissance portrait",
    "Renoir",
    "Retro-Futuristic Suburbia",
    "Rodin",
    "Romanticism",
    "Rothko",
    "Runic Resonance",
    "Sargent",
    "Schiele",
    "Seurat",
    "Shadow Puppetry",
    "Skyward Sculptures",
    "Social Realism",
    "Solar Flare Canvases",
    "Solar Sculptures",
    "Sonic Sculptures",
    "Space Elevator Art",
    "Spectral Cities",
    "Steampunk Acid Circus",
    "Steampunk Cityscape",
    "Subterranean Sanctuaries",
    "Suprematism",
    "Surrealist dream scene",
    "Symbiotic Sculptures",
    "Symbolism",
    "Synesthetic Symphony",
    "Tachisme",
    "Quentin Tarantino-inspired",
    "Techno-Totems",
    "Temporal Tapestries",
    "Terraformed Topographies",
    "Time-Traveling Train Stations",
    "Titian",
    "Toulouse-Lautrec",
    "Traditional Chinese ink painting",
    "Transavantgarde",
    "Turner",
    "Urban Shamanism",
    "Urban exploration",
    "Van Gogh",
    "Velasquez",
    "Vermeer",
    "Victorian gothic horror revival",
    "Victorian-era mechanics",
    "Video art",
    "Virtual Zen Gardens",
    "Vortex Visions",
    "Vorticism",
    "Warhol",
    "Warp Speed Canvases",
    "Whistler",
    "Woven Worlds",
    "Young British Artists",
    "Zombie Formalism",
]

STYLE_PHRASES = [
    "abstract and intricate animal designs",
    "absurdity",
    "acoustical aesthetics",
    "activist messages",
    "aerial artistry",
    "aesthetic errors",
    "african tribal patterns",
    "alien entomology",
    "alien landscapes",
    "altered lifeforms",
    "amazonian tribal art",
    "ancient Egyptian mural",
    "ancient tomorrow",
    "anti-art sentiments",
    "aquatic divination",
    "arcane knowledge",
    "architectural dimensional Dreamscape",
    "aristocratic leisure",
    "art brut",
    "art in harmony with nature",
    "artistically altered planets",
    "assemblage",
    "astral arrangements",
    "astronomical claywork",
    "atomic precision",
    "atomic-age homes",
    "auditory hues",
    "augmented reality overlays",
    "auroral aesthetics",
    "balanced compositions",
    "bauhaus design",
    "below-surface beauty",
    "bioengineered cityscapes",
    "bizarre juxtapositions",
    "black and white contrasts",
    "bold angular forms",
    "bold brush strokes",
    "bold color blocks",
    "bold typography",
    "brass and copper tones",
    "byzantine mosaic",
    "camera-like precision",
    "caribbean palette",
    "cartoon-inspired",
    "cave creations",
    "celestial calligraphy",
    "challenging traditional norms",
    "chiaroscuro lighting",
    "chilly imaginations",
    "chronology structures",
    "cityscapes",
    "classic 50s American diner aesthetics",
    "classical harmony",
    "clean lines",
    "clockwork da Vincis",
    "clockwork locomotives-era transit",
    "cloud-touching creations",
    "collage",
    "color-sound fusion",
    "computer-generated scenes",
    "conceptual art",
    "concrete jungles",
    "confectionary creeps",
    "constructivism",
    "consumer culture symbols",
    "coral-covered ruins",
    "corrupted cityscapes",
    "counter-culture themes",
    "crater canvases",
    "crystal structures",
    "cultural criticism",
    "cultural festivities",
    "cybernetic Michelangelos",
    "cybernetic animals",
    "cybernetic sand patterns",
    "cyclonic creations",
    "decorative motifs",
    "depth-defying canvases",
    "desert wanderers",
    "detailed plant drawings",
    "digital detective stories",
    "digital faeries",
    "digital gargoyles",
    "digital tranquility",
    "digital tribalism",
    "distinct color boundaries",
    "distorted color",
    "diverse materials",
    "doorways to the unknown",
    "dramatic compositions",
    "dramatic lighting",
    "dreamlike imagery",
    "dynamic figures",
    "dystopian themes",
    "early 20th-century",
    "earthy sophistication",
    "eclectic styles",
    "eco-friendly installations",
    "ecological awareness",
    "eerie candlelight",
    "eerie mansions",
    "eight-legged elegance",
    "electric faces",
    "electronic spirits",
    "elegant curves",
    "emotional distortion",
    "emotional resonance",
    "emotive expression",
    "enchanted books",
    "enchanted inscriptions",
    "environmental scale",
    "ephemeral narratives",
    "epic narratives",
    "era-embroidered patterns",
    "era-stacked buildings",
    "esoteric symbols",
    "ethereal atmosphere",
    "ethereal concerts",
    "ethereal luminance",
    "everyday life",
    "everyday materials",
    "evolutionary urbanism",
    "expansive skies",
    "experimental compositions",
    "expressive figures",
    "extraterrestrial flora",
    "fabric galaxies",
    "fantastical amalgamations",
    "ferrofluid designs",
    "fiery palettes",
    "fine brushwork",
    "flat colors",
    "fleeting needlework",
    "floating buildings",
    "floral motifs",
    "flowing radiance",
    "fluid forms",
    "fluorescent flora",
    "folklore fragments",
    "found objects",
    "fragmented objects",
    "free-flowing paint",
    "frontier spirit",
    "frozen luminosity",
    "functional simplicity",
    "fusion of primitive and futuristic elements",
    "futuristic bio-organic architecture",
    "futuristic dystopia",
    "futuristic urban sprawl",
    "gateway art",
    "gear-driven sculptures",
    "gem-inspired architecture",
    "geometric abstraction",
    "geometric patterns",
    "ghostly metropolises",
    "ghostly musicians",
    "glowing fauna",
    "glowing marine life",
    "glowing paths",
    "glowing skies",
    "gold leaf",
    "gothic",
    "grand scale",
    "green-tech environments",
    "hallucinogenic inspiration",
    "haloed figures",
    "haunted portraits",
    "heavenly machinery",
    "heliocentric installations",
    "hieroglyphs",
    "high-tech low-life",
    "historical dramas",
    "historical mashups",
    "history in wood",
    "holographic details",
    "humanist ideals",
    "humorous",
    "hybrid beings",
    "hyper-realistic shadows",
    "ice cream hot fudge sundae dessert landscapes",
    "ice-crafted art",
    "icy spectacles",
    "idea over form",
    "idealized forms",
    "imagined metropolises",
    "indigenous patterns",
    "industrial themes",
    "infinite landscapes",
    "interactive flora",
    "interdimensional imagery",
    "intricate lettering",
    "intricate tile work",
    "iron filings art",
    "ironic sensibility",
    "irreverent style",
    "island landscapes",
    "jazz age influence",
    "jungle scenes",
    "kaleidoscopic designs",
    "kinetic op art",
    "large-scale land alteration",
    "lava-inspired murals",
    "lavish gardens",
    "legendary tiles",
    "levitating designs",
    "light and dark play",
    "light refraction",
    "light-filled mazes",
    "light-speed creations",
    "limited color palette",
    "liquid landscapes",
    "living structures",
    "longships",
    "lost alien civilizations",
    "low-gravity artistry",
    "luminescent landscapes",
    "luminous precipitation",
    "luxurious details",
    "magical experiments",
    "magical symbols",
    "magma tags",
    "magnetic fields in art",
    "makeshift settlements",
    "mammoth herds",
    "marine mysticism",
    "masks",
    "mathematical beauty",
    "mechanical elements",
    "medieval themes",
    "mermaid realms",
    "microscopic sculptures",
    "mind-bending imagery",
    "mineral formations",
    "minimalism",
    "mixed media",
    "modern aesthetic",
    "modernist architecture",
    "molecular landscapes",
    "moon surface installations",
    "moon-based architecture",
    "mountains",
    "movement across planes",
    "mughal miniature painting",
    "multi-layered art",
    "multimedia installations",
    "multiple viewpoints",
    "musical geometry",
    "muted colors",
    "mysterious artifacts",
    "mystical graffiti",
    "mystical laboratories",
    "mythical forest cyber life",
    "mythological scenes",
    "narrative sculptures",
    "natural beauty",
    "natural motifs",
    "nature's power",
    "nature-inspired chic",
    "neo-Tokyo cyberpunk",
    "neoclassicism",
    "neon lights",
    "neon wildlife",
    "neon-lit slums",
    "new perception approaches",
    "nightmare filters",
    "non-Euclidean geometry",
    "non-figurative",
    "non-traditional media",
    "norse mythology",
    "northern lights inspired",
    "nostalgic tomorrow",
    "oceanic curves",
    "optical illusions",
    "optimistic future visions",
    "orbital aesthetics",
    "organic materials",
    "ornamental lines",
    "ornate carving",
    "ornate churches",
    "otherworldly landscapes",
    "outdoor installations",
    "outsider art",
    "overlapping transparent planes",
    "particle patchworks",
    "pastoral paradise",
    "performance art",
    "period costumes with a twist",
    "personal expression",
    "personal mysticism",
    "petrified technology",
    "phantom skylines",
    "physics-inspired fabrics",
    "pixel-based creativity",
    "polar light art",
    "pop surrealism",
    "portals to other realms",
    "post-apocalyptic tribal futurism",
    "pre-raphaelite romanticism",
    "prehistoric survival",
    "primary colors",
    "primitive figures",
    "prismatic effects",
    "probabilistic wildlife",
    "process-focused",
    "profile figures",
    "projected heritage",
    "psychedelic experiences",
    "pyramids",
    "quantum realm abstract art",
    "radiant bursts",
    "radiant portraits",
    "raw aesthetics",
    "raw creativity",
    "readymade objects",
    "realistic details",
    "reclaimed technology",
    "religious themes gone awry",
    "repetitive motifs",
    "retro-futuristic diner on Mars",
    "return to figurative painting",
    "rich textures",
    "robotic handwriting",
    "robotic wildlife",
    "rococo pastoral",
    "romantic scenes",
    "royal courts",
    "rugged terrain",
    "runes",
    "sacred geometry",
    "satellite adornments",
    "scandinavian contemporary design",
    "scientific art",
    "sculpted worlds",
    "sea-inspired art nouveau",
    "self-taught artists",
    "shock tactics",
    "silhouette storytelling",
    "silk-inspired creations",
    "simple forms",
    "simplicity",
    "site-specific",
    "sleek designs",
    "social justice themes",
    "soft brushstrokes",
    "sound-shaped art",
    "space age retro futurism",
    "space opera sets",
    "space station decor",
    "spacecrafts with otherworldly designs",
    "spacefaring arthropods",
    "spacefaring tales",
    "spatial choreography",
    "spectral elegance",
    "spectral symphonies",
    "speed lines",
    "spiderweb designs",
    "spiral aesthetics",
    "spirit animals in the city",
    "spiritual symbolism",
    "spontaneous brushwork",
    "star-forming stitches",
    "star-guided journeys",
    "star-powered robots",
    "starlit dwellings",
    "starry pottery",
    "steam-powered clowns",
    "steam-powered machinery",
    "steampunk inventions",
    "stone-age sci-fi",
    "storytelling reliefs",
    "strong outlines",
    "stylized plants",
    "subatomic particle designs",
    "subconscious art",
    "submerged Victorian cities",
    "sugary scares",
    "sun-powered art",
    "surreal ecosystems",
    "surreal gateways",
    "surreal natural laws",
    "surreal normalcy",
    "surreal steampunk dreamscapes",
    "survivalist themes",
    "suspended structures",
    "sustainable utopias",
    "sweet horror",
    "swirling patterns",
    "tapestry planets",
    "tattooed berzerkers",
    "tattoos",
    "techno-lettering",
    "techno-nature",
    "techno-savannahs",
    "technological exploration",
    "temporal montages",
    "temporal platforms",
    "textile universes",
    "textural abstraction",
    "three-dimensional compositions",
    "time-layered art",
    "time-themed architecture",
    "time-woven fabrics",
    "towering artworks",
    "transient stitches",
    "travel-inspired pixels",
    "trompe-l'oeil realism",
    "tropical scenes",
    "unconventional mediums",
    "underground visual art",
    "underwater luxury",
    "universal harmony",
    "urban expression",
    "velocity visuals",
    "vertical voyages",
    "vibrant contrasts",
    "vibrant distortions",
    "vibrant ecosystems",
    "victorian botanical illustrations",
    "viking",
    "vintage carnival aesthetics",
    "vintage futurism",
    "virtual antiquity",
    "virtual spirituality",
    "virtual voyages",
    "visual conundrums",
    "visual disruptions",
    "visual music",
    "visualizations of quantum physics concepts",
    "visualized soundwaves",
    "vivid colors",
    "volcanic street art",
    "wanderlust web art",
    "water themes",
    "weightless street art",
    "wild brush strokes",
    "woven chronologies",
    "zero-g tags",
]

def generate_random_style():
    base = secrets.choice(STYLE_BASES)
    phrases = ", ".join(secrets.choice(STYLE_PHRASES) for _ in range(secrets.randbelow(3) + 1))
    return f"{base}, {phrases}"

