"""
Dynamic holiday system that computes holidays for any year.

Uses the `holidays` library for official US holidays and custom fixed-date
entries for personal/silly days.
"""

from datetime import date
from typing import Optional

import holidays


def get_us_holidays_for_year(year: int) -> holidays.HolidayBase:
    """Get US holidays including observed days and common additions."""
    us = holidays.US(years=year, observed=True)
    us += holidays.US(years=year, categories=(holidays.UNOFFICIAL,))
    return us


# Custom fixed-date holidays that the `holidays` library doesn't know about.
# These are keyed by (month, day) so they work for any year.
CUSTOM_HOLIDAYS = {
    (1, 6): "Epiphany",
    (1, 7): "International Programmers' Day",
    (2, 15): "Susan B. Anthony's Birthday",
    (3, 2): "Texas Independence Day",
    (3, 8): "International Women's Day",
    (3, 14): "World Kidney Day",
    (3, 17): "St. Patrick's Day",
    (3, 20): "International Day of Happiness",
    (3, 21): "International Day of Forests",
    (3, 22): "World Water Day",
    (4, 10): "Eric and Rachel's Wedding Anniversary",
    (4, 12): "International Day of Human Space Flight",
    (4, 22): "Earth Day",
    (5, 4): "Star Wars Day",
    (5, 5): "Cinco de Mayo",
    (6, 6): "D-Day",
    (6, 14): "Flag Day",
    (6, 19): "Juneteenth",
    (7, 14): "Bastille Day",
    (7, 18): "Nelson Mandela Day",
    (7, 19): "Eric Hamiter Day",
    (7, 20): "World Chess Day",
    (8, 7): "Purple Heart Day",
    (8, 19): "National Aviation Day",
    (8, 22): "Asa Hamiter Day",
    (8, 26): "Women's Equality Day",
    (9, 11): "Patriot Day",
    (9, 17): "Constitution Day",
    (10, 7): "Rachel Daniel Day",
    (10, 9): "Leif Erikson Day",
    (10, 29): "Silas Hamiter Day",
    (10, 31): "Halloween",
    (11, 11): "Veterans Day",
    (12, 6): "St Nicholas Day",
    (12, 7): "Pearl Harbor Remembrance Day",
    (12, 10): "Human Rights Day",
    (12, 17): "Wright Brothers Day",
    (12, 24): "Christmas Eve",
    (12, 31): "New Year's Eve",
}


def get_holiday(date_str: str) -> str:
    """
    Get the holiday for a given date string (YYYY-MM-DD format).
    Returns empty string if no holiday found.
    """
    try:
        year, month, day = map(int, date_str.split("-"))
        d = date(year, month, day)
    except (ValueError, AttributeError):
        return ""

    us_holidays = get_us_holidays_for_year(year)

    if d in us_holidays:
        return us_holidays.get(d)

    custom = CUSTOM_HOLIDAYS.get((month, day))
    if custom:
        return custom

    return ""


# Silly days keyed by (month, day) - these are fun/whimsical days that recur annually
SILLY_DAYS = {
    (1, 1): ["Polar Bear Swim Day"],
    (1, 2): ["Run It Up The Flagpole and See If Anyone Salutes It Day"],
    (1, 3): ["Festival of Sleep Day"],
    (1, 4): ["Trivia Day"],
    (1, 5): ["Bird Day"],
    (1, 6): ["Cuddle Up Day"],
    (1, 7): ["Old Rock Day"],
    (1, 8): ["Bubble Bath Day"],
    (1, 9): ["Static Electricity Day"],
    (1, 10): ["Houseplant Appreciation Day"],
    (1, 11): ["Learn Your Name in Morse Code Day"],
    (1, 12): ["National Pharmacist Day"],
    (1, 13): ["Make Your Dream Come True Day"],
    (1, 14): ["Dress Up Your Pet Day"],
    (1, 15): ["National Hat Day"],
    (1, 16): ["Appreciate A Dragon Day"],
    (1, 17): ["Ditch New Year's Resolutions Day"],
    (1, 18): ["Thesaurus Day"],
    (1, 19): ["Popcorn Day"],
    (1, 20): ["Cheese Lover's Day"],
    (1, 21): ["Hugging Day"],
    (1, 22): ["Answer Your Cat's Questions Day"],
    (1, 23): ["Measure Your Feet Day"],
    (1, 24): ["Compliment Day"],
    (1, 25): ["Opposite Day"],
    (1, 26): ["Peanut Brittle Day"],
    (1, 27): ["Chocolate Cake Day"],
    (1, 28): ["Data Privacy Day"],
    (1, 29): ["Puzzle Day"],
    (1, 30): ["Croissant Day"],
    (1, 31): ["Inspire Your Heart With Art Day"],
    (2, 1): ["Ice Cream for Breakfast Day"],
    (2, 2): ["Groundhog Day"],
    (2, 3): ["Feed the Birds Day"],
    (2, 4): ["Thank a Mail Carrier Day"],
    (2, 5): ["Shower With a Friend Day"],
    (2, 6): ["Pay a Compliment Day"],
    (2, 7): ["Send a Card to a Friend Day"],
    (2, 8): ["Laugh and Get Rich Day"],
    (2, 9): ["Pizza Day"],
    (2, 10): ["Umbrella Day"],
    (2, 11): ["Make a Friend Day"],
    (2, 12): ["Plum Pudding Day"],
    (2, 13): ["Get a Different Name Day"],
    (2, 14): ["Ferris Wheel Day"],
    (2, 15): ["Singles Awareness Day"],
    (2, 16): ["Do a Grouch a Favor Day"],
    (2, 17): ["Random Acts of Kindness Day"],
    (2, 18): ["Battery Day"],
    (2, 19): ["Chocolate Mint Day"],
    (2, 20): ["Love Your Pet Day"],
    (2, 21): ["Sticky Bun Day"],
    (2, 22): ["Be Humble Day"],
    (2, 23): ["Dog Biscuit Appreciation Day"],
    (2, 24): ["Tortilla Chip Day"],
    (2, 25): ["Clam Chowder Day"],
    (2, 26): ["Tell a Fairy Tale Day"],
    (2, 27): ["Polar Bear Day"],
    (2, 28): ["Floral Design Day"],
    (2, 29): ["Leap Day (Hooray!)"],
    (3, 1): ["Peanut Butter Lovers' Day"],
    (3, 2): ["Old Stuff Day"],
    (3, 3): ["If Pets Had Thumbs Day"],
    (3, 4): ["Pancake Day"],
    (3, 5): ["Unique Names Day"],
    (3, 6): ["Oreo Day"],
    (3, 7): ["Be Heard Day"],
    (3, 8): ["Proofreading Day"],
    (3, 9): ["Get Over It Day"],
    (3, 10): ["International Day of Awesomeness"],
    (3, 11): ["Dream Day"],
    (3, 12): ["Plant a Flower Day"],
    (3, 13): ["Smart and Sexy Day"],
    (3, 14): ["Pi Day"],
    (3, 15): ["Brutus Day"],
    (3, 16): ["Everything You Do Is Right Day"],
    (3, 17): ["Corned Beef and Cabbage Day"],
    (3, 18): ["Awkward Moments Day"],
    (3, 19): ["Chocolate Caramel Day"],
    (3, 20): ["International Day of Happiness"],
    (3, 21): ["Common Courtesy Day"],
    (3, 22): ["Goof Off Day"],
    (3, 23): ["Puppy Day"],
    (3, 24): ["Chocolate Covered Raisin Day"],
    (3, 25): ["Waffle Day"],
    (3, 26): ["Make Up Your Own Holiday Day"],
    (3, 27): ["Spanish Paella Day"],
    (3, 28): ["Something on a Stick Day"],
    (3, 29): ["Mom and Pop Business Owners Day"],
    (3, 30): ["Take a Walk in the Park Day"],
    (3, 31): ["World Backup Day"],
    (4, 1): ["April Fool's Day"],
    (4, 2): ["Children's Book Day"],
    (4, 3): ["World Party Day"],
    (4, 4): ["Walk Around Things Day"],
    (4, 5): ["Deep Dish Pizza Day"],
    (4, 6): ["Sorry Charlie Day"],
    (4, 7): ["No Housework Day"],
    (4, 8): ["Draw a Picture of a Bird Day"],
    (4, 9): ["Name Yourself Day"],
    (4, 10): ["Golfers Day"],
    (4, 11): ["Pet Day"],
    (4, 12): ["Grilled Cheese Sandwich Day"],
    (4, 13): ["Scrabble Day"],
    (4, 14): ["Look Up at the Sky Day"],
    (4, 15): ["Rubber Eraser Day"],
    (4, 16): ["Wear Pajamas to Work Day"],
    (4, 17): ["Haiku Poetry Day"],
    (4, 18): ["Animal Crackers Day"],
    (4, 19): ["Garlic Day"],
    (4, 20): ["Look Alike Day"],
    (4, 21): ["Kindergarten Day"],
    (4, 22): ["Jelly Bean Day"],
    (4, 23): ["Talk Like Shakespeare Day"],
    (4, 24): ["Pigs in a Blanket Day"],
    (4, 25): ["Zucchini Bread Day"],
    (4, 26): ["Pretzel Day"],
    (4, 27): ["Babe Ruth Day"],
    (4, 28): ["Blueberry Pie Day"],
    (4, 29): ["Dance Day"],
    (4, 30): ["Honesty Day"],
    (5, 1): ["May Day"],
    (5, 2): ["Truffle Day"],
    (5, 3): ["Paranormal Day"],
    (5, 4): ["Star Wars Day (May the Fourth Be With You)"],
    (5, 5): ["Totally Chipotle Day"],
    (5, 6): ["No Diet Day"],
    (5, 7): ["Paste-Up Day"],
    (5, 8): ["No Socks Day"],
    (5, 9): ["Lost Sock Memorial Day"],
    (5, 10): ["Clean Up Your Room Day"],
    (5, 11): ["Eat What You Want Day"],
    (5, 12): ["Limerick Day"],
    (5, 13): ["Frog Jumping Day"],
    (5, 14): ["Dance Like a Chicken Day"],
    (5, 15): ["Chocolate Chip Day"],
    (5, 16): ["Mimosa Day"],
    (5, 17): ["Pack Rat Day"],
    (5, 18): ["Visit Your Relatives Day"],
    (5, 19): ["Devil's Food Cake Day"],
    (5, 20): ["Be a Millionaire Day"],
    (5, 21): ["Waitstaff Day"],
    (5, 22): ["Buy a Musical Instrument Day"],
    (5, 23): ["Taffy Day"],
    (5, 24): ["Brother's Day"],
    (5, 25): ["Tap Dance Day"],
    (5, 26): ["Paper Airplane Day"],
    (5, 27): ["Cellophane Tape Day"],
    (5, 28): ["Hamburger Day"],
    (5, 29): ["Put a Pillow on Your Fridge Day"],
    (5, 30): ["Water a Flower Day"],
    (5, 31): ["Speak in Complete Sentences Day"],
    (6, 1): ["Say Something Nice Day"],
    (6, 2): ["Leave the Office Early Day"],
    (6, 3): ["Repeat Day (Repeat Day)"],
    (6, 4): ["Cheese Day"],
    (6, 5): ["Hot Air Balloon Day"],
    (6, 6): ["Yo-Yo Day"],
    (6, 7): ["Chocolate Ice Cream Day"],
    (6, 8): ["Best Friends Day"],
    (6, 9): ["Donald Duck Day"],
    (6, 10): ["Iced Tea Day"],
    (6, 11): ["Corn on the Cob Day"],
    (6, 12): ["Red Rose Day"],
    (6, 13): ["Weed Your Garden Day"],
    (6, 14): ["Bourbon Day"],
    (6, 15): ["Smile Power Day"],
    (6, 16): ["Fresh Veggies Day"],
    (6, 17): ["Eat Your Vegetables Day"],
    (6, 18): ["International Picnic Day"],
    (6, 19): ["Garfield the Cat Day"],
    (6, 20): ["Ice Cream Soda Day"],
    (6, 21): ["Selfie Day"],
    (6, 22): ["Chocolate Éclair Day"],
    (6, 23): ["Pink Day"],
    (6, 24): ["Swim a Lap Day"],
    (6, 25): ["Strawberry Parfait Day"],
    (6, 26): ["Beautician's Day"],
    (6, 27): ["Sunglasses Day"],
    (6, 28): ["Insurance Awareness Day"],
    (6, 29): ["Camera Day"],
    (6, 30): ["Meteor Watch Day"],
    (7, 1): ["International Joke Day"],
    (7, 2): ["World UFO Day"],
    (7, 3): ["Stay Out of the Sun Day"],
    (7, 4): ["Sidewalk Egg Frying Day"],
    (7, 5): ["Workaholics Day"],
    (7, 6): ["Take Your Webmaster to Lunch Day"],
    (7, 7): ["Chocolate Day"],
    (7, 8): ["Video Games Day"],
    (7, 9): ["Sugar Cookie Day"],
    (7, 10): ["Don't Step on a Bee Day"],
    (7, 11): ["Cheer Up the Lonely Day"],
    (7, 12): ["Simplicity Day"],
    (7, 13): ["Barbershop Music Appreciation Day"],
    (7, 14): ["Shark Awareness Day"],
    (7, 15): ["Gummi Worm Day"],
    (7, 16): ["World Snake Day"],
    (7, 17): ["Yellow Pig Day"],
    (7, 18): ["National Caviar Day"],
    (7, 19): ["Stick Out Your Tongue Day"],
    (7, 20): ["Moon Day"],
    (7, 21): ["Junk Food Day"],
    (7, 22): ["Hammock Day"],
    (7, 23): ["Vanilla Ice Cream Day"],
    (7, 24): ["Cousins Day"],
    (7, 25): ["Thread the Needle Day"],
    (7, 26): ["All or Nothing Day"],
    (7, 27): ["Take Your Pants for a Walk Day"],
    (7, 28): ["Milk Chocolate Day"],
    (7, 29): ["Lasagna Day"],
    (7, 30): ["Cheesecake Day"],
    (7, 31): ["Uncommon Instrument Awareness Day"],
    (8, 1): ["International Mahjong Day"],
    (8, 2): ["Ice Cream Sandwich Day"],
    (8, 3): ["Watermelon Day"],
    (8, 4): ["Chocolate Chip Cookie Day"],
    (8, 5): ["Work Like a Dog Day"],
    (8, 6): ["Root Beer Float Day"],
    (8, 7): ["Lighthouse Day"],
    (8, 8): ["Sneak Some Zucchini Onto Your Neighbor's Porch Day"],
    (8, 9): ["Book Lovers Day"],
    (8, 10): ["Lazy Day"],
    (8, 11): ["Play in the Sand Day"],
    (8, 12): ["Middle Child Day"],
    (8, 13): ["Left-Handers Day"],
    (8, 14): ["Creamsicle Day"],
    (8, 15): ["Relaxation Day"],
    (8, 16): ["Tell a Joke Day"],
    (8, 17): ["Black Cat Appreciation Day"],
    (8, 18): ["Mail Order Catalog Day"],
    (8, 19): ["Photography Day"],
    (8, 20): ["Lemonade Day"],
    (8, 21): ["Senior Citizens Day"],
    (8, 22): ["Tooth Fairy Day"],
    (8, 23): ["Ride the Wind Day"],
    (8, 24): ["Pluto Demoted Day"],
    (8, 25): ["Banana Split Day"],
    (8, 26): ["Dog Day"],
    (8, 27): ["Just Because Day"],
    (8, 28): ["Bow Tie Day"],
    (8, 29): ["More Herbs, Less Salt Day"],
    (8, 30): ["Toasted Marshmallow Day"],
    (8, 31): ["Trail Mix Day"],
    (9, 1): ["Emma M. Nutt Day"],
    (9, 2): ["Calendar Adjustment Day"],
    (9, 3): ["Skyscraper Day"],
    (9, 4): ["Eat an Extra Dessert Day"],
    (9, 5): ["Be Late for Something Day"],
    (9, 6): ["Read a Book Day"],
    (9, 7): ["Salami Day"],
    (9, 8): ["Ampersand Day"],
    (9, 9): ["Teddy Bear Day"],
    (9, 10): ["Swap Ideas Day"],
    (9, 11): ["Make Your Bed Day"],
    (9, 12): ["Chocolate Milkshake Day"],
    (9, 13): ["Positive Thinking Day", "Roald Dahl Day"],
    (9, 14): ["Cream-Filled Donut Day"],
    (9, 15): ["Felt Hat Day"],
    (9, 16): ["Collect Rocks Day"],
    (9, 17): ["Apple Dumpling Day"],
    (9, 18): ["Cheeseburger Day"],
    (9, 19): ["Talk Like a Pirate Day"],
    (9, 20): ["Punch Day"],
    (9, 21): ["Miniature Golf Day", "Batman Day"],
    (9, 22): ["Hobbit Day"],
    (9, 23): ["Checkers Day"],
    (9, 24): ["Punctuation Day"],
    (9, 25): ["Comic Book Day"],
    (9, 26): ["Love Note Day"],
    (9, 27): ["Crush a Can Day"],
    (9, 28): ["Good Neighbor Day", "Ask a Stupid Question Day"],
    (9, 29): ["Coffee Day"],
    (9, 30): ["Mud Pack Day"],
    (10, 1): ["International Coffee Day"],
    (10, 2): ["Name Your Car Day"],
    (10, 3): ["Techies Day"],
    (10, 4): ["Taco Day", "World Smile Day"],
    (10, 5): ["World Teachers' Day"],
    (10, 6): ["Mad Hatter Day"],
    (10, 7): ["Bathtub Day", "Frappé Day"],
    (10, 8): ["Fluffernutter Day"],
    (10, 9): ["Curious Events Day"],
    (10, 10): ["World Mental Health Day"],
    (10, 11): ["It's My Party Day"],
    (10, 12): ["Old Farmers Day"],
    (10, 13): ["International Skeptics Day", "Train Your Brain Day"],
    (10, 14): ["Ada Lovelace Day"],
    (10, 15): ["I Love Lucy Day"],
    (10, 16): ["Dictionary Day"],
    (10, 17): ["Wear Something Gaudy Day"],
    (10, 18): ["Chocolate Cupcake Day"],
    (10, 19): ["Evaluate Your Life Day"],
    (10, 20): ["Suspenders Day", "International Sloth Day"],
    (10, 21): ["Reptile Awareness Day", "Count your Buttons Day"],
    (10, 22): ["Caps Lock Day", "National Color Day"],
    (10, 23): ["Boston Cream Pie Day", "World Mole Day"],
    (10, 24): ["Bologna Day"],
    (10, 25): ["Punk for a Day Day", "Sourest Day"],
    (10, 26): ["Pumpkin Day", "Howl at the Moon Day and Night"],
    (10, 27): ["Black Cat Day", "American Beer Day"],
    (10, 28): ["Plush Animal Lovers Day", "International Animation Day"],
    (10, 29): ["Internet Day", "National Oatmeal Day"],
    (10, 30): ["Candy Corn Day"],
    (10, 31): ["Carve a Pumpkin Day", "Magic Day"],
    (11, 1): ["Cook for Your Pets Day", "Authors Day"],
    (11, 2): ["Look for Circles Day", "Deviled Eggs Day"],
    (11, 3): ["Sandwich Day", "World Sandwich Day"],
    (11, 4): ["Use Your Common Sense Day"],
    (11, 5): ["Love Your Red Hair Day"],
    (11, 6): ["Saxophone Day"],
    (11, 7): ["Bittersweet Chocolate with Almonds Day", "Men Make Dinner Day"],
    (11, 8): ["Dunce Day", "Tongue Twister Day"],
    (11, 9): ["Chaos Never Dies Day"],
    (11, 10): ["Vanilla Cupcake Day", "Forget Me Not Day"],
    (11, 11): ["Origami Day"],
    (11, 12): ["Happy Hour Day", "National French Dip Day"],
    (11, 13): ["World Kindness Day", "Sadie Hawkins Day"],
    (11, 14): ["Pickle Day", "Spicy Guacamole Day"],
    (11, 15): ["Clean Out Your Refrigerator Day"],
    (11, 16): ["Fast Food Day"],
    (11, 17): ["Take a Hike Day"],
    (11, 18): ["Mickey Mouse Day", "Push Button Phone Day"],
    (11, 19): ["Have a Bad Day Day"],
    (11, 20): ["Name Your PC Day", "National Absurdity Day"],
    (11, 21): ["World Television Day", "Use Less Stuff Day", "World Hello Day"],
    (11, 22): ["Go For a Ride Day", "Buy Nothing Day"],
    (11, 23): ["Fibonacci Day"],
    (11, 24): ["Celebrate Your Unique Talent Day"],
    (11, 25): ["Shopping Reminder Day"],
    (11, 26): ["Cake Day", "National Cake Day"],
    (11, 27): ["Pins and Needles Day"],
    (11, 28): ["French Toast Day", "Red Planet Day"],
    (11, 29): ["Electronic Greetings Day"],
    (11, 30): ["Stay Home Because You're Well Day", "Computer Security Day"],
    (12, 1): ["Eat a Red Apple Day"],
    (12, 2): ["Fritters Day"],
    (12, 3): ["Roof Over Your Head Day"],
    (12, 4): ["Wear Brown Shoes Day", "Santa's List Day"],
    (12, 5): ["Bathtub Party Day", "Day of the Ninja"],
    (12, 6): ["Put On Your Own Shoes Day", "Microwave Oven Day"],
    (12, 7): ["Letter Writing Day", "National Cotton Candy Day"],
    (12, 8): ["Pretend To Be A Time Traveler Day", "National Brownie Day"],
    (12, 9): ["Christmas Card Day", "Weary Willie Day"],
    (12, 10): ["Dewey Decimal System Day", "Nobel Prize Day"],
    (12, 11): ["Noodle Ring Day"],
    (12, 12): ["Gingerbread House Day", "National Ding-a-Ling Day"],
    (12, 13): ["Ice Cream Day"],
    (12, 14): ["Monkey Day", "Official Lost and Found Day"],
    (12, 15): ["Cat Herders Day"],
    (12, 16): ["Chocolate Covered Anything Day"],
    (12, 17): ["Wright Brothers Day"],
    (12, 18): ["Answer The Telephone Like Buddy The Elf Day"],
    (12, 19): ["Look for an Evergreen Day"],
    (12, 20): ["Sangria Day", "Underdog Day"],
    (12, 21): ["Ugly Sweater Day", "International Dalek Remembrance Day"],
    (12, 22): ["Date Nut Bread Day"],
    (12, 23): ["Festivus"],
    (12, 24): ["National Eggnog Day"],
    (12, 25): ["Grav Mass Day", "A'phabet Day or No 'L' Day"],
    (12, 26): ["Thank You Note Day"],
    (12, 27): ["No Interruptions Day"],
    (12, 28): ["Card Playing Day"],
    (12, 29): ["Pepper Pot Day"],
    (12, 30): ["Bacon Day"],
    (12, 31): ["Make Up Your Mind Day"],
}


def get_silly_day(date_str: str) -> str:
    """
    Get silly day(s) for a given date string (YYYY-MM-DD format).
    Returns formatted string with Oxford comma if multiple days.
    """
    try:
        year, month, day = map(int, date_str.split("-"))
    except (ValueError, AttributeError):
        return ""

    events = SILLY_DAYS.get((month, day), [])

    if not events:
        return ""

    if len(events) > 2:
        return ", ".join(events[:-1]) + ", and " + events[-1]
    else:
        return " and ".join(events)


def get_todays_holidays_display(date_str: str) -> str:
    """
    Get combined holiday and silly day display string for a given date.
    """
    holiday = get_holiday(date_str)
    silly_day = get_silly_day(date_str)

    if holiday and silly_day:
        return f"{holiday}, {silly_day}"
    return holiday or silly_day
